### ISSUE TITLE
Device : Samsung Series 7 : UE55NU7025

### ISSUE THREAD

**Issue by bapt814** [jhonpetter/SamsungSmartTwitchApp#1]
Cmd -> sdb.exe capability
C:\Users\bapti\Downloads\app.Twitch>sdb.exe capability
secure_protocol:enabled
intershell_support:disabled
filesync_support:push
usbproto_support:disabled
sockproto_support:enabled
syncwinsz_support:enabled
sdbd_rootperm:disabled
rootonoff_support:disabled
encryption_support:disabled
zone_support:disabled
multiuser_support:enabled
cpu_arch:armv7
sdk_toolpath:/home/owner/share/tmp/sdk_tools
profile_name:tv
vendor_name:Samsung
can_launch:tv-samsung
device_name:Tizen
platform_version:4.0
product_version:4.0
sdbd_version:2.2.31
sdbd_plugin_version:3.4.1_TV_REL
sdbd_cap_version:1.0
log_enable:disabled
log_path:/tmp
appcmd_support:disabled
appid2pid_support:enabled
pkgcmd_debugmode:enabled

**Comment by jhonpetter** [comment]
your tv is compatible
